uavcan.node.id:
  type: Integer
  note: Defines a node-ID. Allowed values [0,127].
  enum: PARAM_UAVCAN_NODE_ID
  flags: mutable
  default: 42
  min: 0
  max: 255

system.name:
  type: String
  note: Defines custom node name.
  enum: PARAM_SYSTEM_NAME
  flags: mutable
  default: "arl.lights"

lights.id:
  type: Integer
  note: Defines the lights id. The default value is zero, which for PX4 0 means UI LED.
  enum: PARAM_LIGHTS_ID
  flags: mutable
  default: 0
  min: 0
  max: 255

lights.max_intensity:
  type: Integer
  note: Defines the max intensity of the lights [%].
  enum: PARAM_LIGHTS_MAX_INTENSITY
  flags: mutable
  default: 2
  min: 0
  max: 100

lights.default_color:
  type: Integer
  note: Defines a default color of the lights. 0 - red, 1 - green, 2 - blue, 3 - cyan, 4 - magenta, 5 - yellow, 6 - white, 7 - turned off
  enum: PARAM_LIGHTS_DEFAULT_COLOR
  flags: mutable
  default: 0
  min: 0
  max: 6

lights.type:
  type: Integer
  note: Defines an intensity transition rate of the lights. 0 - solid (steady and continuous illumination), 1 - blinking (rapid on-off cycling of colors), 2 - pulsing (gradual increase and decrease in brightness or color intensity).
  enum: PARAM_LIGHTS_TYPE
  flags: mutable
  default: 2
  min: 0
  max: 255

lights.period:
  type: Integer
  note: Defines a blink period of the lights [ms]. This parameter has no effect when lights.type=0 (solid)
  enum: PARAM_LIGHTS_PERIOD_MS
  flags: mutable
  default: 1000
  min: 1
  max: 65535


lights.duty_cycle_pct:
  type: Integer
  note: Defines a duty cycle of the lights [%].
  enum: PARAM_LIGHTS_DUTY_CYCLE_PTC
  flags: mutable
  default: 50
  min: 0
  max: 100

lights.verbose:
  type: Integer
  note: Indicates the operational mode of the node. 
  When set to 1, the uavcan.equipment.indication.LightsCommand will be transmitted, including the current LED color and id. 
  enum: PARAM_LIGHTS_VERBOSE
  flags: mutable
  default: 0
  min: 0
  max: 1