name: code_style

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  cpplint:
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: pip3 install cpplint
      - name: cpplint
        run: |
          all_diff=$(git diff --name-only origin/main)
          printf "All diff:\n$all_diff\n\n"

          cpp_diff=$(echo "$all_diff" | grep -E '\.(cpp|c|hpp|h)$') || true
          if [ ! -z "$cpp_diff" ]; then
            printf "C++ diff:\n$cpp_diff\n\n"
          fi

          if [ ! -z "$cpp_diff" ]; then
            echo "cpplint:"
            cpplint $cpp_diff
          fi
